project:
  type: website

website:
  title: "Capitol Area Food Protection Association"
  navbar:
    left:
      - href: board.qmd
        text: Board Members
      - href: fall2026meeting.qmd
        text: ASM & CAFPA Fall 2026 Meeting

  announcement:
    icon: info-circle
    dismissable: true
    content: "**Upcoming** - ASM & CAFPA Fall 2026 Joint Meeting - Oct. 23rd - [Learn more and register](fall2026meeting.qmd)"
    type: success
    position: below-navbar

format:
  html:
    theme:
      - flatly
    css: styles.css
    toc: false



